import 'package:flutter/material.dart';

// const Color COLOR_PRIMARY = Color(0xFF222222);
const Color COLOR_PRIMARY = Color(0xFF035ded);
// const Color COLOR_PRIMARY = Color(0xFFff6f00);
const Color COLOR_WHITE   = Color(0xFFFFFFFF);
const Color COLOR_BLACK   = Color(0xFF000000);
const Color COLOR_SECONDARY = Color(0xFF);
const Color COLOR_TEXTCOLORPRIMARY = Color(0xFF212121);
const Color COLOR_TEXT_PRIMARY = Color(0xFF130925);
const Color COLOR_TEXTCOLORSECONDARY = Color(0xFF5A5C5E);
const Color COLOR_TEXT_DATE =Color(0xFF203afb);
const Color COLOR_BACKGROUNDCOLOR = Color(0xFFF0F4FF);
const Color COLOR_GREY = Color(0xFF808080);
const Color COLOR_GREY_666 = const Color(0xFF666666);
const Color COLOR_DARK_GREY = const Color(0xFF444444);
const Color COLOR_SHADOW = Color(0x95E9EBF0);
const Color COLOR_DIVIDER = Color(0xFFDADADA);
const Color COLOR_DIVIDER_V2 = Color(0xFFedf8ff);
const Color COLOR_YELLOW = Color(0xFFff7100);
const Color COLOR_RED_V2 = const Color(0xFFFF0000);
const Color COLOR_TEXT_Color_Secondary_V2 = Color(0xFF757575);
const Color COLOR_LIGHT_GREY_EEE = const Color(0xFFEEEEEE);
const Color COLOR_LIGHT_GREY_F6 = const Color(0xFFF6F6F6);
const Color COLOR_PRIMARY_LIGHT = Color(0x505104D7);

const Color COLOR_BACKGROUND_PINK = Color(0xFFe6637a);
const Color COLOR_BACKGROUND_PINK_TRANS = Color(0xFFffe2e9);
const Color COLOR_BACKGROUND_GREEN = Color(0xFF42e8a7);
const Color COLOR_BACKGROUND_GREEN_TRANS = Color(0xFFe3ffef);
